# -*- coding: utf-8 -*-
"""TareaProgra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8-XIN-M_vySO-SgwPXkzmvQsHxoM1L8

• ¿Qué es un paradigma de programación?

Es una forma de enfocar un lenguajes de programación para estructuras programas con ciertas características propias, proporcionando técnicas y metolodogías para diseñar soluciones a problemas con un estilo especifico de pensamiento.


• ¿En qué se basa la programación orientada a objetos?

La programación oritentada a objetos (POO) es uno de los paradigmas de programación más utilizados debido a sus características inherentes, que facilitan tanto el desarrollo de aplicaciones sencillas como complejas. Se distingue por su enfoque en la organización del software a través de "objetos" y "clases", lo que permite crear programas modulares y representar de manera eficiente conceptos del mundo real mediante la abstracción de datos y la agrupación de información.

• ¿Cuál es la diferencia entre recursividad e iteración, y cómo se relaciona esto con la notación big 𝑂?

Tanto la recursividad como la iteración son conceptos relacionados a la existencia de un bucle, el cual se repite múltiple veces hasta cumplir con un objetivo previamente establecido.

La diferencia entre ambas radica en su estructura.La recursividad se define de tal forma que una función se llame a si misma cuando no se cumple con los casos base, es decir, la ejecución del cuerpo de una función recursiva puede requerir la aplicación de dicha función varias veces con el fin de resolver el problema.

Por otra parte, los bucles iterativos se caracterizan por repetir el mismo procedimiento varias veces. Entre ellos, se destacan el bucle "for", que repite el procedimiento un número determinado de veces, y el bucle "while", que repite el procedimiento hasta que se cumpla una condición específica.

Con respecto a su relacion con la notación big O, la elección de como estructurar un programa para resolver un problema es crucial para la eficiencia del algoritmo. Big O es una forma de expresar la complejidad de un algoritmo en términos de eficiencia, por lo que decidir entre usar un bucle iterativo o uno recursivo influye a la notación big O del programa.


• explicar la diferencia de rendimiento entre 𝑂(1) y 𝑂(𝑛)

Big O es una forma de comparar la eficiencia de distintos enfoques de un problema, el cuál considera distintos factores para clasificar la eficiencia del programa, como la complejidad en funciónd del tamaño de la entrada, la independencia de la máquina y el "working storage".

O(1) significa que el número de operaciones que debe realizar el algoritmo para completar una tarea determinada es independiente del tamaño de la entrada, siendo el tipo de algoritmo más rápido. Por otra parte, un programa 0(n) es de tiempo lineal, por lo que crece directamente proporcional al tamaño de su entrada.  

• ¿Cómo se calcula el orden en un programa que funciona por etapas?

Se debe ver el orden de cada etapa del programa para luego compararlos entre ellos. Los términos están dominados entre ellos según el tiempo en que tardan en resolver su función, por lo que el orden del programa es igual al de mayor dominancia según: O(1) < O(log(n)) < O(n) < O(nlog(n)) < O(n2) < O(2n) < O(n!)

• ¿Cómo se puede determinar la complejidad temporal de un algoritmo recursivo?

Para determinar la complejidad temporal de un algoritmo recursivo se debe resolver una ecuación llamada "relación de recurrencia", la cual expresa el tiempo de ejecución del algoritmo en términos de si mismo. Para resolverla hay distintas técnicas, como el método de árbol de recurrencia o el teorema maestro.
"""

import time
import matplotlib.pyplot as plt
from math import factorial

#Primera forma:
# Creamos una matriz de NxM llena de 1. La idea de este método se basa en el hecho que solo se puede avanzar hacia la derecha o hacia abajo
# Esto implica que todos los caminos posibles para llegar a una celda son en realidad la suma de los caminos posbiles para llegar a la celda de arriba más los caminos para llegar a la celda de abajo

def Metodo1(n, m):
    matriz = [[1 for x in range(m)] for y in range(n)]      # Creamos una matriz NxM solo de 1
    for i in range(1, n):
        for j in range(1, m):
            matriz[i][j] = matriz[i-1][j] + matriz[i][j-1]   # Caminos para llegar a la celda actual = Caminos para llegar a la celda de la izquierda + Caminos para llegar a la celda de arriba
    return matriz[-1][-1]

# Segunda Forma:
# Ahora, tras analizar la solución creado por medio de bucles iterativos, nos podemos dar cuenta que el problema también puede ser resuelto de una forma matemática.
# Debemos entender que para cualquier matriz NxM, para llegar a la esquina inferior derecha se deben realizar (N-1) movimientos hacia abajo y (M-1) movimientos hacia la derecha.
# Esto implica que el resultado sea equivalente a realizar una permutación con repetición.

def Metodo2(m, n):
    numerador = factorial(n + m - 2)
    denominador = factorial(n - 1) * factorial(m - 1)
    return int(numerador / denominador)

# Configuraciones de tamaños de grilla
n_values = [5, 10, 15, 20, 25]
m_values = [5, 10, 15, 20, 25]

# Almacenamiento de resultados
results1 = []
results2 = []

for n, m in zip(n_values, m_values):
    start_time = time.time()
    Metodo1(n, m)
    end_time = time.time()
    results1.append(end_time - start_time)

    start_time = time.time()
    Metodo2(m, n)
    end_time = time.time()
    results2.append(end_time - start_time)

# Creación del gráfico
plt.figure(figsize=(10, 5))
plt.plot(n_values, results1, label='Metodo 1')
plt.plot(m_values, results2, label='Metodo 2')
plt.xlabel('Dimension de la grilla (NxM)')
plt.ylabel('Tiempo de ejecución (segundos)')
plt.title('Comparación del tiempo de ejecución de los Métodos 1 y 2')
plt.legend()
plt.grid(True)

# Guardar el gráfico en formato SVG
plt.savefig('tiempos_de_ejecucion.svg')

plt.show()